# Generated by Django 5.2 on 2025-04-21 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='music',
            name='author',
        ),
        migrations.AlterField(
            model_name='music',
            name='genre',
            field=models.CharField(max_length=100),
        ),
    ]
