# Generated by Django 5.2 on 2025-05-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_author_is_deleted_music_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
