# Generated by Django 5.2 on 2025-04-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_update_at_music_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.IntegerField(),
        ),
    ]
