# Generated by Django 5.2 on 2025-05-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_rename_update_at_author_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='music_audios/'),
        ),
    ]
