# Generated by Django 5.2 on 2025-04-25 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_author_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.author'),
        ),
    ]
